FROM --platform=linux/amd64 ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# Update and install required packages
RUN apt-get -y update && \
    apt-get install -y wget gnupg software-properties-common libnotify4 && \
    apt install -y python3-pip python3-dev ipython3 && \
    python3 -m pip install ipykernel && \
    python3 -m ipykernel install && \
    pip3 install pylint

RUN pip3 install --upgrade pip

# torch, lightgbm need older versions of crytography and pyOpenSSL
#RUN pip uninstall cryptography pyOpenSSL
#RUN pip install cryptography==3.4.6 pyOpenSSL==21.0.0 bob tools
#RUN pip install cryptography pyOpenSSL bob tools

RUN pip3 install numpy scipy pandas matplotlib scikit-learn==1.2.0 Scrapy beautifulsoup4 eli5 pipenv structure chainer bob tools
# pybrain - not compatible with scipy?? It is old and last maintained on 2015.
# Theano - needs numpy <= 1.20.3 (obsolute)
# ramp - needs configuration are < python3
# Unsuccessful -  nupic caffe2

# The GPU packages
RUN  pip install tensorflow torch lightgbm Keras pyodm chainer cupy-cuda12x

RUN cd /tmp && \
    wget https://az764295.vo.msecnd.net/stable/6ab598523be7a800d7f3eb4d92d7ab9a66069390/code_1.39.2-1571154070_amd64.deb && \
    dpkg -i code_1.39.2-1571154070_amd64.deb && \
    rm -f code_1.39.2-1571154070_amd64.deb

ENTRYPOINT $*
